name: CI

on:
  pull_request:
    branches: [ "main" ]
    
defaults:
 run:
  working-directory: ./src
    
jobs:
  publish:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'CosmosDb.Migrator.sln'

    runs-on: windows-latest
    timeout-minutes: 15
    
    steps:
    - name: Start CosmosDb Emulator
      uses: southpolesteve/cosmos-emulator-github-action@v1

    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
      
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Restore dependencies
      run: nuget restore ${{ env.SOLUTION }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION }} --configuration ${{ env.BUILD_CONFIG }} --no-restore

    - name: Run tests
      run: dotnet test /p:Configuration=${{ env.BUILD_CONFIG }} --no-restore --no-build --verbosity normal
